### ISSUE TITLE
Milestone:3 -Form-section

### ISSUE THREAD

**Issue by derrick1451** [alphayowakarindi/My-Portfolio#4]
### Highlights

- Linter checks passed
- Well organized code
- Descriptive readme files
- ### changes :recycle: 
- Add a label element on the input form to improve the SEO and accessibility to other users(impaired users)
- Use only width on the image element such that the image is responsive
- Factories the input elements in the CSS to avoid redundant code 
- Use max-width on the child elements to make it responsive

**Comment by alphayowakarindi** [comment]
Hi, thank you for the fantastic changes, I have fixed these changes in https://github.com/alphayowakarindi/My-Portfolio/pull/8
